<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<script scr="js/jquery.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- Optional theme -->

		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

		<title>Menu </title>

	</head>
	<body>
		<img class="img-responsive" src="../Imagenes/imagen2.png"/>
		<div class="container">
		          <div class="col-xs-2">
            <div class="thumbnail">
                <img src="../Imagenes/lotes.jpg" alt="imagen">
                <div class="caption">
                    <h3>LOTES</h3>
                    <p>
                        <a href="http://localhost:8080/Ecuaforestar/Usuarios/Lotes/INGRESOL.php" class="btn btn-primary">Acceder</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-xs-2">
            <div class="thumbnail">
                <img src="../Imagenes/guayusa.jpg" alt="imagen">
                <div class="caption">
                    <h3>PLANTAS</h3>
                    <p>
                        <a href="http://localhost:8080/Ecuaforestar/Usuarios/Plantas/INGRESO.PHP" class="btn btn-primary">Acceder</a>               
                    </p>
                </div>
            </div>
        </div>
        <div class="col-xs-2">
            <div class="thumbnail">
                <img src="../Imagenes/productos.jpg" alt="imagen">
                <div class="caption">
                    <h3>PRODUCTOS</h3>      
                    <p>
                        <a href="http://localhost:8080/Ecuaforestar/Usuarios/Productos/INGRESOP.php" class="btn btn-primary">Acceder</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-xs-2">
            <div class="thumbnail">
                <img src="../Imagenes/platita.jpg" alt="imagen">
                <div class="caption">
                    <h3>REGISTRO DE SIEMBRA</h3>            
                    <p>
                        <a href="http://localhost:8080/Ecuaforestar/Usuarios/PlantasLotes/INGRESOV.php" class="btn btn-primary">Acceder</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col-xs-2">
            <div class="thumbnail">
                <img src="../Imagenes/aplicaciones.jpg" alt="imagen">
                <div class="caption">
                    <h3>APLICACION DE PRODUCTOS</h3>            
                    <p>
                        <a href="http://localhost:8080/Ecuaforestar/Usuarios/Aplicaciones/INGRESOA.php" class="btn btn-primary">Acceder</a>                 
                    </p>
                </div>
            </div>
        </div>
<div class="container">


</div>
<h3>CONSULTAS</h3>            
                    <p>
                        <a href="http://localhost:8080/Ecuaforestar/Usuarios/Consultas/CONSULTAS.php" class="btn btn-primary">Acceder</a>                 
                    </p>
        </body>
		</div>

</html>